// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIyOEN0kvbFLeF3x8Kv6kADmzR-US99L8',
    appId: '1:457797490593:web:9c937a0af278cbf64b9de0',
    messagingSenderId: '457797490593',
    projectId: 'xboite-d7c80',
    authDomain: 'xboite-d7c80.firebaseapp.com',
    storageBucket: 'xboite-d7c80.firebasestorage.app',
    measurementId: 'G-PED2CM44CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Ab1IkCU0tpEkclalxx3t2eb76odNuAk',
    appId: '1:457797490593:android:75ca728094d772c94b9de0',
    messagingSenderId: '457797490593',
    projectId: 'xboite-d7c80',
    storageBucket: 'xboite-d7c80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4u5aX5vlthQcy-krx72eL1MHZPx2GPU',
    appId: '1:457797490593:ios:03689fb6771d98854b9de0',
    messagingSenderId: '457797490593',
    projectId: 'xboite-d7c80',
    storageBucket: 'xboite-d7c80.firebasestorage.app',
    iosBundleId: 'com.equilibre.sboite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4u5aX5vlthQcy-krx72eL1MHZPx2GPU',
    appId: '1:457797490593:ios:68f54c444b28e0ef4b9de0',
    messagingSenderId: '457797490593',
    projectId: 'xboite-d7c80',
    storageBucket: 'xboite-d7c80.firebasestorage.app',
    iosBundleId: 'com.example.immobilierApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIyOEN0kvbFLeF3x8Kv6kADmzR-US99L8',
    appId: '1:457797490593:web:2ca99ac8bbfc0c5b4b9de0',
    messagingSenderId: '457797490593',
    projectId: 'xboite-d7c80',
    authDomain: 'xboite-d7c80.firebaseapp.com',
    storageBucket: 'xboite-d7c80.firebasestorage.app',
    measurementId: 'G-2RHGWCFH68',
  );
}